import { lazy, Suspense, useEffect, useMemo, useState } from "react";
import { Link, Navigate, useLocation, useNavigate, useParams } from "react-router-dom";
import {
  Activity, ArrowRight, BadgeCheck, BarChart3, Bot, Box, BriefcaseBusiness, CalendarDays,
  Check, ChevronRight, CircleDollarSign, Clock3, Copy, FileBadge, FileDown, Gauge,
  GraduationCap, LayoutDashboard, LockKeyhole, Megaphone, PackagePlus, Pencil,
  MessageSquareText, Plus, QrCode, Radio, Rocket, Save, ScanLine, School, Send, Settings2, Share2,
  ShieldCheck, ShoppingBag, Sparkles, Target, TrendingUp, Trophy, Users, WalletCards, Wifi, Zap,
} from "lucide-react";
import { agents, marketplaceOffers, missions, podTypes, roles, sponsorConfig, tenantConfig, type Role } from "../data";
import { getAnalytics, getBadges, getProofs, shareCertificate, trackEvent, validateProof } from "../platform";
import { useAMX } from "../AppContext";
import { ControlCard, EmptyState, Metric, PageHeader, ProofStatus, QRCodeCard, StatusPill, XPBar } from "../components";
import { canAccess, getActiveTenant, getMissionDrafts, getPods, joinPod, recordCampaignEvent, saveMissionDraft, savePod, updateMissionDraft, updatePod, type SkillPod } from "../operations";
import { useRealtimeRoom } from "../realtime";
import { getTenantRecord } from "../tenant-management";

const LiveKitPod = lazy(() => import("../LiveKitPod").then((module) => ({ default: module.LiveKitPod })));

export function WalletPage() {
  const {xp}=useAMX();const proofs=getProofs();const badges=getBadges();const tenant=getTenantRecord(getActiveTenant());const [tab,setTab]=useState<"proofs"|"badges"|"certificates">("proofs");
  return <div className="page section-wrap"><PageHeader eyebrow="PORTABLE PROOF" title="Proof wallet" description="Your verified runs, badges, reports, and certificates stay connected." actions={<button className="button secondary"><Share2/>Share profile</button>}/>
    <section className="wallet-header"><div><span className="eyebrow">RUNWAY ID</span><h2>guest-user</h2><p>{tenant.certificateName} / Learner credential path</p></div><XPBar value={xp}/><div className="wallet-totals"><div><b>{badges.length}</b><span>BADGES</span></div><div><b>{proofs.length}</b><span>PROOFS</span></div><div><b>{proofs.filter((p)=>p.certificate.issued).length}</b><span>CERTIFICATES</span></div></div></section>
    <div className="tab-row">{(["proofs","badges","certificates"] as const).map((item)=><button className={tab===item?"active":""} onClick={()=>setTab(item)} key={item}>{item}</button>)}</div>
    {tab==="proofs"&&(proofs.length?<div className="proof-list">{proofs.map((proof)=><article className="proof-card" key={proof.id}>{proof.mediaProofUrl&&<img className="proof-thumb" src={proof.mediaProofUrl} alt="Captured spatial mission proof"/>}<div className="proof-icon"><ShieldCheck/></div><div><span className="eyebrow">{proof.program}</span><h3>{proof.project}</h3><p>{new Date(proof.timestamp).toLocaleString()} / {proof.role} / {proof.report.score}%</p><code>{proof.id} / {proof.signature}</code></div><div className="proof-card-status"><ProofStatus status={proof.status==="in_progress"?"In progress":proof.syncStatus==="queued"?"Queued":validateProof(proof)?"Signature valid":"Review required"}/><button className="icon-button" aria-label="Copy proof id" onClick={()=>navigator.clipboard.writeText(proof.id)}><Copy/></button></div></article>)}</div>:<EmptyState icon={ShieldCheck} title="No proof records yet" body="Complete your first mission to create a portable OPPRRC record." action={<Link to="/missions" className="button primary">Find a mission</Link>}/>)}
    {tab==="badges"&&<div className="badge-grid">{badges.map((badge,index)=><article className="wallet-badge" key={badge}><div className="mini-badge"><Trophy/></div><StatusPill tone={index===0?"gold":"cyan"}>{index===0?"NEWEST":"EARNED"}</StatusPill><h3>{badge}</h3><p>AMX AIR Hubs verified credential</p></article>)}</div>}
    {tab==="certificates"&&<div className="certificate-list">{proofs.filter((p)=>p.certificate.issued).map((proof)=><article key={proof.id}><FileBadge/><div><h3>{proof.certificate.badge}</h3><p>Certificate ready / {new Date(proof.timestamp).toLocaleDateString()}</p></div><button className="button secondary" onClick={()=>shareCertificate(proof)}><FileDown/>Download</button></article>)}</div>}
  </div>;
}

export function MarketplacePage() {
  const [filter,setFilter]=useState("All");const tenant=getTenantRecord(getActiveTenant());const scopedOffers=marketplaceOffers.filter((offer)=>tenant.marketplaceOfferIds.includes(offer.id));const types=["All",...new Set(scopedOffers.map((offer)=>offer.type))];const visible=scopedOffers.filter((offer)=>filter==="All"||offer.type===filter);
  return <div className="page marketplace-page section-wrap"><PageHeader eyebrow={`${tenant.name.toUpperCase()} MARKETPLACE`} title="Turn proof into opportunity" description="Continue learning, join a cohort, deploy an agent, or fund the next verified outcome."/>
    <div className="market-spotlight"><div><StatusPill tone="gold">RECOMMENDED NEXT</StatusPill><span className="eyebrow">PROJECT OPERATIONS</span><h2>Project Checklist with TAZ</h2><p>Use your XRT foundation to scope and sequence a real project run.</p><Link to="/mission/project-checklist/pre" className="button primary">Open next mission<ArrowRight/></Link></div><div className="market-signal"><BriefcaseBusiness/><span>+160 XP</span><b>TAZ</b></div></div>
    <div className="filter-row">{types.map((type)=><button key={type} className={filter===type?"active":""} onClick={()=>setFilter(type)}>{type}</button>)}</div>
    <div className="offer-grid">{visible.length ? visible.map((offer,index)=><article key={offer.id}><div className="offer-number">{String(index+1).padStart(2,"0")}</div><span className="eyebrow">{offer.type}</span><h3>{offer.title}</h3><p>{offer.detail}</p><button className="button ghost full" onClick={()=>trackEvent("marketplace_click",{tenantId:tenant.id})}>{offer.cta}<ChevronRight/></button></article>) : <EmptyState icon={ShoppingBag} title="No offers enabled" body="This organization has not enabled marketplace offers." action={<Link className="button secondary" to="/tenants">Configure organization</Link>}/>}</div>
  </div>;
}

export function PodsPage() {
  const {role}=useAMX();const [room,setRoom]=useState("");const [selected,setSelected]=useState(podTypes[1]);const [pods,setPods]=useState(getPods);const [activePod,setActivePod]=useState<SkillPod|undefined>(pods[0]);const [joinStatus,setJoinStatus]=useState("");const [message,setMessage]=useState("");
  const live=useRealtimeRoom(activePod?.code);
  const create=()=>{const pod=savePod({name:`${selected.title} / XRT Green Mode`,type:selected.id,missionId:"xrt-green-mode",agents:["jaz","taz"]});setPods(getPods());setActivePod(pod);trackEvent("pod_created",{missionId:pod.missionId,role})};
  const join=()=>{const pod=joinPod(room);if(pod){setJoinStatus(`Joined ${pod.name}`);setActivePod(pod);setPods(getPods())}else setJoinStatus("Room code not found")};
  const approve=()=>{if(!activePod||!canAccess(role,"approve"))return;updatePod(activePod.id,{trainerApproved:true,status:"complete"});const next=getPods();setPods(next);setActivePod(next.find((pod)=>pod.id===activePod.id))};
  return <div className="page section-wrap"><PageHeader eyebrow="SHARED XR ROOMS" title="Skill Pods" description="Launch a guided mission for one learner, a team, a classroom, or a sponsor cohort." actions={<button className="button primary" onClick={create}><Plus/>Create pod</button>}/>
    <div className="pod-layout"><div className="pod-types">{podTypes.map((pod)=><button className={selected.id===pod.id?"selected":""} key={pod.id} onClick={()=>setSelected(pod)}><span className="pod-icon">{pod.id==="teams"?<School/>:<Users/>}</span><div><h3>{pod.title}</h3><p>{pod.detail}</p><span>{pod.seats} {pod.seats===1?"seat":"seats"}</span></div>{selected.id===pod.id&&<Check/>}</button>)}</div>
    <aside className="room-console"><div className="room-radar"><span/><i/><b>{Math.max(activePod?.participants.length||0,live.peers.length)}</b></div><div className="room-live"><span className="live-dot"/><b>{activePod?"ROOM ACTIVE":"ROOM PREVIEW"}</b><small><Wifi/>{live.transport}</small></div><h2>{activePod?.name||selected.title}</h2><div className="room-code"><span>ROOM CODE</span><strong>{activePod?.code||"------"}</strong><button className="icon-button" disabled={!activePod} onClick={()=>activePod&&navigator.clipboard.writeText(activePod.code)}><Copy/></button></div><div className="room-roster"><div><span>GUIDES</span><b>{activePod?.agents.join(" + ").toUpperCase()||"JAZ + TAZ"}</b></div><div><span>PARTICIPANTS</span><b>{Math.max(activePod?.participants.length||0,live.peers.length)} active</b></div><div><span>APPROVAL</span><b>{activePod?.trainerApproved?"Trainer approved":"Trainer required"}</b></div></div>{activePod&&canAccess(role,"approve")?<button className="button primary large full" onClick={approve} disabled={activePod.trainerApproved}><ShieldCheck/>{activePod.trainerApproved?"Run approved":"Approve completion"}</button>:<button className="button primary large full" onClick={create}><Radio/>Launch room</button>}</aside></div>
    {activePod&&<Suspense fallback={<div className="pod-camera-off"><Radio/><span>Preparing room media</span></div>}><LiveKitPod roomCode={activePod.code} agents={agents.filter((agent)=>activePod.agents.includes(agent.id)).concat(agents).filter((agent,index,list)=>list.findIndex((item)=>item.id===agent.id)===index).slice(0,3)}/></Suspense>}
    {activePod&&<section className="room-feed"><div className="room-feed-head"><div><span className="eyebrow">LIVE ROOM CHANNEL</span><h2>Pod communications</h2></div><StatusPill tone={live.transport==="websocket"?"green":"cyan"}>{live.transport}</StatusPill></div><div className="room-messages">{live.messages.length?live.messages.map((item)=><div key={item.id}><MessageSquareText/><p><b>{item.sender===live.participantId?"You":item.sender}</b> {item.text}</p><time>{new Date(item.timestamp).toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"})}</time></div>):<p>Room events and team messages will appear here.</p>}</div><form className="room-compose" onSubmit={(event)=>{event.preventDefault();live.send(message);setMessage("")}}><input aria-label="Room message" value={message} onChange={(event)=>setMessage(event.target.value)} placeholder="Message the pod"/><button className="button primary" disabled={!message.trim()}><Send/>Send</button></form></section>}
    <section className="join-room"><div><span className="eyebrow">HAVE A ROOM CODE?</span><h2>Join an active Skill Pod</h2>{joinStatus&&<p>{joinStatus}</p>}</div><div><input value={room} onChange={(event)=>setRoom(event.target.value.toUpperCase())} maxLength={6} placeholder="ABC123"/><button disabled={room.length<6} className="button secondary" onClick={join}>Join pod<ArrowRight/></button></div></section>
    {pods.length>0&&<section className="pod-history"><div className="section-heading"><div><span className="eyebrow">SAVED ROOMS</span><h2>Pod operations</h2></div></div>{pods.map((pod)=><button key={pod.id} onClick={()=>setActivePod(pod)}><div><b>{pod.name}</b><span>{pod.code} / {pod.participants.length} participants</span></div><StatusPill tone={pod.status==="complete"?"green":"cyan"}>{pod.status}</StatusPill><ChevronRight/></button>)}</section>}
  </div>;
}

export function SponsorPage() {
  const m=sponsorConfig.metrics;const completion=Math.round((m.completions/m.starts)*100);
  return <div className="page sponsor-page section-wrap"><PageHeader eyebrow="SPONSOR ACTIVATION" title="Fund outcomes you can verify" description="AMX connects every campaign scan to a mission, certificate, and marketplace next step." actions={<button className="button primary"><Megaphone/>Sponsor this mission</button>}/>
    <div className="sponsor-hero"><div><div className="sponsor-logo large">AMX<span>LABS</span></div><StatusPill tone="green">CAMPAIGN LIVE</StatusPill><h2>XRT Community Runway</h2><p>One QR campaign activating WebXR training across schools, community centers, and partner events.</p><div className="campaign-tags"><span>CAMPAIGN {sponsorConfig.campaignId}</span><span>SPONSORED ACCESS</span></div></div><QRCodeCard route="/sponsor/amx-labs/xrt-green-mode" title="Sponsor Activation"/></div>
    <div className="signal-grid sponsor-metrics"><Metric label="QR scans" value={m.scans.toLocaleString()} delta="+18% this month" icon={QrCode}/><Metric label="Mission starts" value={m.starts} delta="73.6% of scans" icon={Rocket}/><Metric label="Completions" value={m.completions} delta={completion+"% completion"} icon={BadgeCheck}/><Metric label="Certificates" value={m.certificates} delta="96.5% issued" icon={FileBadge}/></div>
    <div className="roi-layout"><section className="roi-chart"><div className="section-heading"><div><span className="eyebrow">ACTIVATION FUNNEL</span><h2>From attention to proof</h2></div></div>{[{label:"Scans",value:m.scans,color:"#55e6ff"},{label:"Starts",value:m.starts,color:"#79eea8"},{label:"Completions",value:m.completions,color:"#f4c96b"},{label:"Marketplace",value:m.marketplaceConversions,color:"#ff7a66"}].map((item)=><div className="funnel-row" key={item.label}><span>{item.label}</span><div><i style={{width:`${item.value/m.scans*100}%`,background:item.color}}/></div><b>{item.value}</b></div>)}</section><aside className="roi-card"><CircleDollarSign/><span className="eyebrow">COST PER VERIFIED COMPLETION</span><strong>${m.costPerCompletion.toFixed(2)}</strong><p>Includes mission access, badge, certificate, and sponsor outcome report.</p><button className="button secondary full">Download ROI brief<FileDown/></button></aside></div>
  </div>;
}

export function AdminPage() {
  const {role}=useAMX();const [items,setItems]=useState(getMissionDrafts);const [open,setOpen]=useState(false);
  const [form,setForm]=useState({title:"",description:"",domain:"Education",role:"Learner" as Role,agentId:"jaz",steps:"Briefing\nInteractive checkpoint\nProof review",quiz:"What proves this mission is complete?",badge:"AMX Mission Builder",rewardXP:100,sponsor:"",opprrcCategory:"Education",accessType:"free",modelName:""});
  const set=(key:keyof typeof form,value:string|number)=>setForm((current)=>({...current,[key]:value}));
  const create=()=>{if(!form.title.trim())return;saveMissionDraft({title:form.title,description:form.description,domain:form.domain,roles:[form.role],agentId:form.agentId,steps:form.steps.split("\n").filter(Boolean),quiz:form.quiz,badge:form.badge,rewardXP:Number(form.rewardXP),sponsor:form.sponsor,opprrcCategory:form.opprrcCategory,accessType:form.accessType,modelName:form.modelName,published:false});setItems(getMissionDrafts());setOpen(false);trackEvent("mission_draft_created",{role})};
  const publish=(id:string)=>{if(!canAccess(role,"publish"))return;updateMissionDraft(id,{published:true});setItems(getMissionDrafts());trackEvent("mission_published",{role})};
  return <div className="page section-wrap"><PageHeader eyebrow="ADMIN / MISSION BUILDER" title="Mission control" description="Configure missions, QR launch routes, agents, proof, and tenant publishing." actions={<button className="button primary" onClick={()=>setOpen(true)}><PackagePlus/>New mission</button>}/>
    <div className="admin-summary"><Metric label="Published missions" value={missions.length+items.filter((item)=>item.published).length} delta="Tenant catalog" icon={Radio}/><Metric label="Draft missions" value={items.filter((item)=>!item.published).length} delta="JSON mission config" icon={Pencil}/><Metric label="Enabled agents" value={tenantConfig.enabledAgents.length} delta={tenantConfig.name} icon={Bot}/><Metric label="Proof review" value={getProofs().filter((proof)=>proof.status==="in_progress").length} delta="Runs awaiting closeout" icon={ShieldCheck}/></div>
    {role!=="Admin"&&<div className="permission-banner"><LockKeyhole/><div><b>Admin role required for publishing</b><span>You can build and preview drafts. Switch to Admin to publish them.</span></div><Link className="button secondary" to="/role">Change role</Link></div>}
    <div className="admin-layout"><section className="admin-table"><div className="table-head"><span>MISSION</span><span>AGENT</span><span>ACCESS</span><span>STATUS</span><span/></div>{missions.map((mission)=><div className="table-row" key={mission.id}><div><b>{mission.title}</b><small>{mission.domain}</small></div><span>{mission.agentId.toUpperCase()}</span><StatusPill tone={mission.access.type==="sponsored"?"gold":"cyan"}>{mission.access.type}</StatusPill><StatusPill tone="green">Published</StatusPill><Link className="icon-button" to={`/scan/${mission.id}`}><QrCode/></Link></div>)}{items.map((mission)=><div className="table-row" key={mission.id}><div><b>{mission.title}</b><small>{mission.domain} / {mission.steps.length} steps</small></div><span>{mission.agentId.toUpperCase()}</span><StatusPill tone={mission.accessType==="sponsored"?"gold":"neutral"}>{mission.accessType}</StatusPill><StatusPill tone={mission.published?"green":"gold"}>{mission.published?"Published":"Draft"}</StatusPill><button className="icon-button" title="Publish mission" disabled={mission.published||!canAccess(role,"publish")} onClick={()=>publish(mission.id)}>{mission.published?<Check/>:<Rocket/>}</button></div>)}</section>
    <aside className="tenant-panel"><span className="eyebrow">ACTIVE TENANT</span><h2>{tenantConfig.name}</h2><code>{tenantConfig.id}</code><dl><div><dt>Default mission</dt><dd>{tenantConfig.defaultMission}</dd></div><div><dt>Agents</dt><dd>{tenantConfig.enabledAgents.length} enabled</dd></div><div><dt>Features</dt><dd>{tenantConfig.enabledFeatures.length} active</dd></div></dl><button className="button secondary full"><Settings2/>Tenant settings</button></aside></div>
    {open&&<div className="modal-backdrop"><div className="builder-modal wide"><span className="eyebrow">JSON MISSION CONFIG</span><h2>Create mission draft</h2><div className="builder-grid"><label>Mission title<input value={form.title} onChange={(event)=>set("title",event.target.value)} placeholder="Community History AR"/></label><label>Domain<input value={form.domain} onChange={(event)=>set("domain",event.target.value)}/></label><label className="span-2">Description<textarea value={form.description} onChange={(event)=>set("description",event.target.value)} placeholder="Describe the mission outcome."/></label><label>Primary role<select value={form.role} onChange={(event)=>set("role",event.target.value)}>{roles.map((item)=><option value={item.id} key={item.id}>{item.id}</option>)}</select></label><label>Guide agent<select value={form.agentId} onChange={(event)=>set("agentId",event.target.value)}>{agents.map((item)=><option key={item.id} value={item.id}>{item.name} / {item.role}</option>)}</select></label><label className="span-2">Mission steps<textarea value={form.steps} onChange={(event)=>set("steps",event.target.value)}/></label><label className="span-2">Quiz question<input value={form.quiz} onChange={(event)=>set("quiz",event.target.value)}/></label><label>Badge<input value={form.badge} onChange={(event)=>set("badge",event.target.value)}/></label><label>Reward XP<input type="number" value={form.rewardXP} onChange={(event)=>set("rewardXP",Number(event.target.value))}/></label><label>Sponsor<input value={form.sponsor} onChange={(event)=>set("sponsor",event.target.value)}/></label><label>Access type<select value={form.accessType} onChange={(event)=>set("accessType",event.target.value)}>{["free","paid","sponsored","member","trainer","cohort"].map((value)=><option key={value}>{value}</option>)}</select></label><label>OPPRRC category<input value={form.opprrcCategory} onChange={(event)=>set("opprrcCategory",event.target.value)}/></label><label>3D model<input type="file" accept=".glb,.gltf" onChange={(event)=>set("modelName",event.target.files?.[0]?.name||"")}/><small>{form.modelName||"GLB or GLTF metadata is stored with the draft."}</small></label></div><div className="modal-actions"><button className="button ghost" onClick={()=>setOpen(false)}>Cancel</button><button className="button primary" onClick={create}><Save/>Save draft</button></div></div></div>}
  </div>;
}

export function AnalyticsPage() {
  const events=getAnalytics();const counts=(name:string)=>events.filter((event)=>event.eventName===name).length;const synthetic=events.length===0;
  const data=synthetic?{views:1284,starts:946,places:901,checkpoints:2436,complete:812}:{views:counts("mission_viewed"),starts:counts("mission_started"),places:counts("agent_placed"),checkpoints:counts("checkpoint_completed"),complete:counts("mission_completed")};
  const max=Math.max(data.views,1);
  return <div className="page section-wrap"><PageHeader eyebrow="RUNWAY INTELLIGENCE" title="Analytics dashboard" description={synthetic?"Demo tenant performance. Live device events replace these values as missions run.":"Live events captured on this device."} actions={<StatusPill tone="green">LOCAL-FIRST</StatusPill>}/>
    <div className="admin-summary"><Metric label="Total scans" value={data.views} delta="QR and direct launches" icon={QrCode}/><Metric label="Mission starts" value={data.starts} delta={Math.round(data.starts/max*100)+"% conversion"} icon={Rocket}/><Metric label="Completions" value={data.complete} delta={Math.round(data.complete/Math.max(data.starts,1)*100)+"% completion"} icon={BadgeCheck}/><Metric label="Marketplace clicks" value={counts("marketplace_click")||196} delta="24% of completers" icon={ShoppingBag}/></div>
    <div className="analytics-layout"><section className="analytics-chart"><div className="section-heading"><div><span className="eyebrow">MISSION FUNNEL</span><h2>Run progression</h2></div><button className="button ghost"><CalendarDays/>Last 30 days</button></div><div className="bar-chart">{Object.entries(data).map(([label,value])=><div key={label}><div className="bar-value">{value}</div><div className="bar-shell"><i style={{height:`${Math.max(8,value/max*100)}%`}}/></div><span>{label}</span></div>)}</div></section><aside className="agent-performance"><span className="eyebrow">AGENT PERFORMANCE</span><h2>Completion by guide</h2>{agents.slice(0,4).map((agent,index)=><div className="agent-row" key={agent.id}><span className="agent-dot" style={{background:agent.color}}/><div><b>{agent.name}</b><span>{agent.role}</span></div><strong>{[91,86,78,83][index]}%</strong></div>)}</aside></div>
  </div>;
}

export function ControlPage() {
  return <div className="page section-wrap"><PageHeader eyebrow="AMX COCKPIT" title="Runway control" description="Operate rooms, missions, agents, proof, partner activation, and reporting from one surface."/><div className="control-grid"><ControlCard icon={Gauge} title="Production status" text="Inspect readiness, storage, media, rooms, agents, and gateways." to="/control/runtime"/><ControlCard icon={Box} title="Nexus spatial ops" text="Run the Blender room, LiveKit media, fleet, and geospatial anchors." to="/nexus"/><ControlCard icon={PackagePlus} title="Mission builder" text="Create, configure, preview, and publish." to="/admin"/><ControlCard icon={QrCode} title="QR campaign studio" text="Generate tracked mission, event, and sponsor routes." to="/qr-studio"/><ControlCard icon={BarChart3} title="Analytics" text="Track scans, runs, proof, and conversion." to="/analytics"/><ControlCard icon={Users} title="Skill Pods" text="Launch shared rooms and group missions." to="/pods"/><ControlCard icon={Megaphone} title="Sponsor layer" text="Model branded activation and ROI." to="/sponsor"/><ControlCard icon={WalletCards} title="Proof vault" text="Review OPPRRC records and certificates." to="/wallet"/><ControlCard icon={LayoutDashboard} title="Tenant console" text="Scope missions, agents, branding, and reports." to="/tenants"/><ControlCard icon={Bot} title="Agent registry" text="Assign voices, specialties, and missions." to="/agents"/></div></div>;
}

export function ScanResolver() {
  const params=useParams();const location=useLocation();const navigate=useNavigate();const {setActiveMissionId}=useAMX();const slug=params["*"]?.split("/").pop()||"xrt-green-mode";const mission=missions.find((item)=>item.id===slug)||missions[0];const query=new URLSearchParams(location.search);const campaignId=query.get("campaign")||undefined;const locationTag=query.get("location")||undefined;
  useEffect(()=>{trackEvent("qr_scan",{missionId:mission.id,campaignId,locationTag});if(campaignId){localStorage.setItem("amx_active_campaign",campaignId);recordCampaignEvent(campaignId,"scans")}if(locationTag)localStorage.setItem("amx_active_location",locationTag);setActiveMissionId(mission.id);const timer=setTimeout(()=>navigate(`/mission/${mission.id}/pre`,{replace:true}),900);return()=>clearTimeout(timer)},[campaignId,locationTag,mission.id,navigate,setActiveMissionId]);
  return <div className="scan-resolver"><div className="scan-pulse"><ScanLine/></div><span className="eyebrow">QR ROUTE RESOLVED</span><h1>{mission.title}</h1><p>Loading agent, tenant, sponsor, and mission configuration.</p></div>;
}

export function SponsorResolver(){const params=useParams();const location=useLocation();const slug=params["*"]?.split("/").pop()||"xrt-green-mode";return <Navigate to={`/scan/${slug}${location.search}`} replace/>}
