CREATE TABLE IF NOT EXISTS lms_programs (id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL, title TEXT NOT NULL, mode TEXT NOT NULL, status TEXT NOT NULL, payload TEXT NOT NULL, created_by TEXT NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS lms_programs_tenant_idx ON lms_programs (tenant_id, status, updated_at);

CREATE TABLE IF NOT EXISTS lms_enrollments (id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL, program_id TEXT NOT NULL, learner_id TEXT NOT NULL, learner_name TEXT NOT NULL, status TEXT NOT NULL, completed_module_ids TEXT NOT NULL DEFAULT '[]', attendance_minutes INTEGER NOT NULL DEFAULT 0, evidence_count INTEGER NOT NULL DEFAULT 0, score INTEGER NOT NULL DEFAULT 0, earned_cents INTEGER NOT NULL DEFAULT 0, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, UNIQUE (tenant_id, program_id, learner_id));
CREATE INDEX IF NOT EXISTS lms_enrollments_program_idx ON lms_enrollments (tenant_id, program_id, status, updated_at);
CREATE INDEX IF NOT EXISTS lms_enrollments_learner_idx ON lms_enrollments (tenant_id, learner_id, updated_at);

CREATE TABLE IF NOT EXISTS lms_activity_events (id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL, program_id TEXT NOT NULL, enrollment_id TEXT NOT NULL, module_id TEXT NOT NULL, event_type TEXT NOT NULL, value INTEGER NOT NULL, actor_id TEXT NOT NULL, payload TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS lms_activity_events_enrollment_idx ON lms_activity_events (tenant_id, enrollment_id, created_at);

INSERT OR IGNORE INTO lms_programs (id, tenant_id, title, mode, status, payload, created_by, created_at, updated_at) VALUES (
  'future-skills-live-runway', 'tech-at-nite', 'Future Skills Live Runway', 'market_sim', 'published',
  '{"id":"future-skills-live-runway","tenantId":"tech-at-nite","title":"Future Skills Live Runway","summary":"Train, rehearse, prove, and promote a community production team into a paid XR showcase.","mode":"market_sim","status":"published","facilitator":"JAZ + AMX Operator","modules":[{"id":"ai-production-brief","title":"AI Production Brief","stage":"learn","summary":"Build a responsible show brief with agent guidance.","durationMinutes":35,"unlockAfterModuleId":null,"availableAt":null,"missionId":"ai-101","liveRoom":null,"rewardXp":100,"rewardCents":0},{"id":"pod-rehearsal","title":"Pod Rehearsal","stage":"practice","summary":"Assign roles, route media, and rehearse cues in a live Pod.","durationMinutes":55,"unlockAfterModuleId":"ai-production-brief","availableAt":null,"missionId":"automations","liveRoom":"NEXUS1","rewardXp":140,"rewardCents":0},{"id":"operator-proof","title":"Operator Proof","stage":"prove","summary":"Submit run-of-show, tool traces, and reflection for approval.","durationMinutes":30,"unlockAfterModuleId":"pod-rehearsal","availableAt":null,"missionId":null,"liveRoom":null,"rewardXp":175,"rewardCents":0},{"id":"expo-showcase","title":"Expo Showcase","stage":"live","summary":"Promote the approved run to the AMX XR Stage.","durationMinutes":45,"unlockAfterModuleId":"operator-proof","availableAt":null,"missionId":null,"liveRoom":"AMXSTAGE","rewardXp":225,"rewardCents":0},{"id":"paid-production-run","title":"Paid Production Run","stage":"earn","summary":"Operator-approved project settlement through the earning ledger.","durationMinutes":60,"unlockAfterModuleId":"expo-showcase","availableAt":null,"missionId":null,"liveRoom":null,"rewardXp":250,"rewardCents":7500}]}',
  'system', datetime('now'), datetime('now')
);
